const cards = [
  {
    img: 'img to cards.jpg',
    id: 1,
    title: 'Card 1',
    description: 'This is the description for card 1.',
  },
  {
    img: 'img to cards.jpg',
    id: 2,
    title: 'Card 2',
    description: 'This is the description for card 2.',
  },
  {
    img: 'img to cards.jpg',
    id: 3,
    title: 'Card 3',
    description: 'This is the description for card 3.',
  },
  {
    img: 'img to cards.jpg',
    id: 4,
    title: 'Card 4',
    description: 'This is the description for card 4.',
  },
  {
    img: 'img to cards.jpg',
    id: 5,
    title: 'Card 5',
    description: 'This is the description for card 5.',
  },
  {
    img: 'img to cards.jpg',
    id: 6,
    title: 'Card 6',
    description: 'This is the description for card 6.',
  },
  {
    img: 'img to cards.jpg',
    id: 7,
    title: 'Card 7',
    description: 'This is the description for card 7.',
  },
  {
    img: 'img to cards.jpg',
    id: 8,
    title: 'Card 8',
    description: 'This is the description for card 8.',
  },
  {
    img: 'img to cards.jpg',
    id: 9,
    title: 'Card 9',
    description: 'This is the description for card 9.',
  },
  {
    img: 'img to cards.jpg',
    id: 10,
    title: 'Card 10',
    description: 'This is the description for card 10.',
  },
  {
    img: 'img to cards.jpg',
    id: 11,
    title: 'Card 11',
    description: 'This is the description for card 11.',
  },
  {
    img: 'img to cards.jpg',
    id: 12,
    title: 'Card 12',
    description: 'This is the description for card 12.',
  },
  {
    img: 'img to cards.jpg',
    id: 13,
    title: 'Card 13',
    description: 'This is the description for card 13.',
  },
  {
    img: 'img to cards.jpg',
    id: 14,
    title: 'Card 14',
    description: 'This is the description for card 14.',
  },
  {
    img: 'img to cards.jpg',
    id: 15,
    title: 'Card 15',
    description: 'This is the description for card 15.',
  },
  {
    img: 'img to cards.jpg',
    id: 16,
    title: 'Card 16',
    description: 'This is the description for card 16.',
  },
  {
    img: 'img to cards.jpg',
    id: 17,
    title: 'Card 17',
    description: 'This is the description for card 17.',
  },
  {
    img: 'img to cards.jpg',
    id: 18,
    title: 'Card 18',
    description: 'This is the description for card 18.',
  },
  {
    img: 'img to cards.jpg',
    id: 19,
    title: 'Card 19',
    description: 'This is the description for card 19.',
  },
  {
    img: 'img to cards.jpg',
    id: 20,
    title: 'Card 20',
    description: 'This is the description for card 20.',
  },
  {
    img: 'img to cards.jpg',
    id: 21,
    title: 'Card 22',
    description: 'This is the description for card 20.',
  },
  {
    img: 'img to cards.jpg',
    id: 22,
    title: 'Card 222',
    description: 'This is the description for card 20.',
  },
]
